
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Pasien      <small><?= cclang('detail', ['Pasien']); ?> </small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/pasien'); ?>">Pasien</a></li>
      <li class="active"><?= cclang('detail'); ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Pasien</h3>
                     <h5 class="widget-user-desc">Detail Pasien</h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal form-step" name="form_pasien" id="form_pasien" >
                  
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Idpasien </label>

                        <div class="col-sm-8">
                        <span class="detail_group-idpasien"><?= _ent($pasien->idpasien); ?></span>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">NoRM </label>

                        <div class="col-sm-8">
                        <span class="detail_group-noRM"><?= _ent($pasien->noRM); ?></span>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Nik </label>

                        <div class="col-sm-8">
                        <span class="detail_group-nik"><?= _ent($pasien->nik); ?></span>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Jenis Kelamin </label>

                        <div class="col-sm-8">
                        <span class="detail_group-jkelamin"><?= _ent($pasien->jkelamin); ?></span>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Tanggal Lahir </label>

                        <div class="col-sm-8">
                        <span class="detail_group-tanggal_lahir"><?= _ent($pasien->tanggal_lahir); ?></span>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Alamat </label>

                        <div class="col-sm-8">
                        <span class="detail_group-alamat"><?= _ent($pasien->alamat); ?></span>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Jenis Asuransi </label>

                        <div class="col-sm-8">
                        <span class="detail_group-jenis_asuransi"><?= _ent($pasien->jenis_asuransi); ?></span>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">DPJP </label>

                        <div class="col-sm-8">
                        <span class="detail_group-dpjp"><?= _ent($pasien->dpjp); ?></span>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Ruang </label>

                        <div class="col-sm-8">
                        <span class="detail_group-ruang"><?= _ent($pasien->ruang); ?></span>
                        </div>
                    </div>
                                        
                    <br>
                    <br>


                     
                         
                    <div class="view-nav">
                        <?php is_allowed('pasien_update', function() use ($pasien){?>
                        <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit pasien (Ctrl+e)" href="<?= site_url('administrator/pasien/edit/'.$pasien->idpasien); ?>"><i class="fa fa-edit" ></i> <?= cclang('update', ['Pasien']); ?> </a>
                        <?php }) ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/pasien/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list_button', ['Pasien']); ?></a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->

<script>
$(document).ready(function(){
   (function(){
        var noRM = $('.detail_group-noRM');
        var nik = $('.detail_group-nik');
        var jkelamin = $('.detail_group-jkelamin');
        var tanggal_lahir = $('.detail_group-tanggal_lahir');
        var alamat = $('.detail_group-alamat');
        var jenis_asuransi = $('.detail_group-jenis_asuransi');
        var dpjp = $('.detail_group-dpjp');
        var ruang = $('.detail_group-ruang');
    })()
      
   });
</script>