
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>

<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+a', function assets() {
       window.location.href = BASE_URL + '/administrator/Form_dekubitus/add';
       return false;
   });

   $('*').bind('keydown', 'Ctrl+f', function assets() {
       $('#sbtn').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
       $('#reset').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+b', function assets() {

       $('#reset').trigger('click');
       return false;
   });
}

jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      <?= cclang('form_dekubitus') ?><small><?= cclang('list_all'); ?></small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active"><?= cclang('form_dekubitus') ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
      
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">
               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                     <div class="row pull-right">
                        <?php is_allowed('form_dekubitus_add', function(){?>
                        <a class="btn btn-flat btn-success btn_add_new" id="btn_add_new" title="<?= cclang('add_new_button', [cclang('form_dekubitus')]); ?>  (Ctrl+a)" href="<?=  site_url('administrator/form_dekubitus/add'); ?>"><i class="fa fa-plus-square-o" ></i> <?= cclang('add_new_button', [cclang('form_dekubitus')]); ?></a>
                        <?php }) ?>
                        <?php is_allowed('form_dekubitus_export', function(){?>
                        <a class="btn btn-flat btn-success" title="<?= cclang('export'); ?> <?= cclang('form_dekubitus') ?> " href="<?= site_url('administrator/form_dekubitus/export?q='.$this->input->get('q').'&f='.$this->input->get('f')); ?>"><i class="fa fa-file-excel-o" ></i> <?= cclang('export'); ?> XLS</a>
                        <?php }) ?>
                                             </div>
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/list.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username"><?= cclang('form_dekubitus') ?></h3>
                     <h5 class="widget-user-desc"><?= cclang('list_all', [cclang('form_dekubitus')]); ?>  <i class="label bg-yellow"><?= $form_dekubitus_counts; ?>  <?= cclang('items'); ?></i></h5>
                  </div>

                  <form name="form_form_dekubitus" id="form_form_dekubitus" action="<?= base_url('administrator/form_dekubitus/index'); ?>">
                  


                     <!-- /.widget-user -->
                  <div class="row">
                     <div class="col-md-8">
                                                <div class="col-sm-2 padd-left-0 " >
                           <select type="text" class="form-control chosen chosen-select" name="bulk" id="bulk" placeholder="Site Email" >
                                                         <option value="delete">Delete</option>
                                                      </select>
                        </div>
                        <div class="col-sm-2 padd-left-0 ">
                           <button type="button" class="btn btn-flat" name="apply" id="apply" title="<?= cclang('apply_bulk_action'); ?>"><?= cclang('apply_button'); ?></button>
                        </div>
                                                <div class="col-sm-3 padd-left-0  " >
                           <input type="text" class="form-control" name="q" id="filter" placeholder="<?= cclang('filter'); ?>" value="<?= $this->input->get('q'); ?>">
                        </div>
                        <div class="col-sm-3 padd-left-0 " >
                           <select type="text" class="form-control chosen chosen-select" name="f" id="field" >
                              <option value=""><?= cclang('all'); ?></option>
                               <option <?= $this->input->get('f') == 'nama_pasien' ? 'selected' :''; ?> value="nama_pasien">Nama Pasien</option>
                            <option <?= $this->input->get('f') == 'nama_ruangan' ? 'selected' :''; ?> value="nama_ruangan">Nama Ruangan</option>
                            <option <?= $this->input->get('f') == 'Tanggal_lahir' ? 'selected' :''; ?> value="Tanggal_lahir">Tanggal Lahir</option>
                            <option <?= $this->input->get('f') == 'Tanggal' ? 'selected' :''; ?> value="Tanggal">Tanggal</option>
                            <option <?= $this->input->get('f') == 'Jam' ? 'selected' :''; ?> value="Jam">Jam</option>
                            <option <?= $this->input->get('f') == 'Jenis_kelamin' ? 'selected' :''; ?> value="Jenis_kelamin">Jenis Kelamin</option>
                            <option <?= $this->input->get('f') == 'kondisi_fisik' ? 'selected' :''; ?> value="kondisi_fisik">Kondisi Fisik</option>
                            <option <?= $this->input->get('f') == 'status_mental' ? 'selected' :''; ?> value="status_mental">Status Mental</option>
                            <option <?= $this->input->get('f') == 'aktifitas' ? 'selected' :''; ?> value="aktifitas">Aktifitas</option>
                            <option <?= $this->input->get('f') == 'mobilitas' ? 'selected' :''; ?> value="mobilitas">Mobilitas</option>
                            <option <?= $this->input->get('f') == 'inkontinensia' ? 'selected' :''; ?> value="inkontinensia">Inkontinensia</option>
                           </select>
                        </div>
                        <div class="col-sm-1 padd-left-0 ">
                           <button type="submit" class="btn btn-flat" name="sbtn" id="sbtn" value="Apply" title="<?= cclang('filter_search'); ?>">
                           Filter
                           </button>
                        </div>
                        <div class="col-sm-1 padd-left-0 ">
                           <a class="btn btn-default btn-flat" name="reset" id="reset" value="Apply" href="<?= base_url('administrator/form_dekubitus');?>" title="<?= cclang('reset_filter'); ?>">
                           <i class="fa fa-undo"></i>
                           </a>
                        </div>
                     </div>
                     <div class="col-md-4">
                        <div class="dataTables_paginate paging_simple_numbers pull-right" id="example2_paginate" >
                           <?= $pagination; ?>
                        </div>
                     </div>
                  </div>
                  <div class="table-responsive"> 

                  <br>
                  <table class="table table-bordered table-striped dataTable">
                     <thead>
                        <tr class="">
                                                     <th>
                            <input type="checkbox" class="flat-red toltip" id="check_all" name="check_all" title="check all">
                           </th>
                                                    <th data-field="nama_pasien"data-sort="1" data-primary-key="0"> <?= cclang('nama_pasien') ?></th>
                           <th data-field="nama_ruangan"data-sort="1" data-primary-key="0"> <?= cclang('nama_ruangan') ?></th>
                           <th data-field="Tanggal_lahir"data-sort="1" data-primary-key="0"> <?= cclang('Tanggal_lahir') ?></th>
                           <th data-field="Tanggal"data-sort="1" data-primary-key="0"> <?= cclang('Tanggal') ?></th>
                           <th data-field="Jam"data-sort="1" data-primary-key="0"> <?= cclang('Jam') ?></th>
                           <th data-field="Jenis_kelamin"data-sort="1" data-primary-key="0"> <?= cclang('Jenis_kelamin') ?></th>
                           <th data-field="kondisi_fisik"data-sort="1" data-primary-key="0"> <?= cclang('kondisi_fisik') ?></th>
                           <th data-field="status_mental"data-sort="1" data-primary-key="0"> <?= cclang('status_mental') ?></th>
                           <th data-field="aktifitas"data-sort="1" data-primary-key="0"> <?= cclang('aktifitas') ?></th>
                           <th data-field="mobilitas"data-sort="1" data-primary-key="0"> <?= cclang('mobilitas') ?></th>
                           <th data-field="inkontinensia"data-sort="1" data-primary-key="0"> <?= cclang('inkontinensia') ?></th>
                           <th>Action</th>                        </tr>
                     </thead>
                     <tbody id="tbody_form_dekubitus">
                     <?php foreach($form_dekubituss as $form_dekubitus): ?>
                        <tr>
                                                       <td width="5">
                              <input type="checkbox" class="flat-red check" name="id[]" value="<?= $form_dekubitus->idform_dekubitus; ?>">
                           </td>
                                                       
                           <td><span class="list_group-nama_pasien"><?= _ent($form_dekubitus->nama_pasien); ?></span></td> 
                           <td><span class="list_group-nama_ruangan"><?= _ent($form_dekubitus->nama_ruangan); ?></span></td> 
                           <td><span class="list_group-Tanggal_lahir"><?= _ent($form_dekubitus->Tanggal_lahir); ?></span></td> 
                           <td><span class="list_group-Tanggal"><?= _ent($form_dekubitus->Tanggal); ?></span></td> 
                           <td><span class="list_group-Jam"><?= _ent($form_dekubitus->Jam); ?></span></td> 
                           <td><span class="list_group-Jenis_kelamin"><?= _ent($form_dekubitus->Jenis_kelamin); ?></span></td> 
                           <td><span class="list_group-kondisi_fisik"><?= _ent($form_dekubitus->kondisi_fisik); ?></span></td> 
                           <td><span class="list_group-status_mental"><?= _ent($form_dekubitus->status_mental); ?></span></td> 
                           <td><span class="list_group-aktifitas"><?= _ent($form_dekubitus->aktifitas); ?></span></td> 
                           <td><span class="list_group-mobilitas"><?= _ent($form_dekubitus->mobilitas); ?></span></td> 
                           <td><span class="list_group-inkontinensia"><?= _ent($form_dekubitus->inkontinensia); ?></span></td> 
                           <td width="200">
                            
                                                              <?php is_allowed('form_dekubitus_view', function() use ($form_dekubitus){?>
                                                              <a href="<?= site_url('administrator/form_dekubitus/view/' . $form_dekubitus->idform_dekubitus); ?>" class="label-default"><i class="fa fa-newspaper-o"></i> <?= cclang('view_button'); ?>
                              <?php }) ?>
                              <?php is_allowed('form_dekubitus_update', function() use ($form_dekubitus){?>
                              <a href="<?= site_url('administrator/form_dekubitus/edit/' . $form_dekubitus->idform_dekubitus); ?>" class="label-default"><i class="fa fa-edit "></i> <?= cclang('update_button'); ?></a>
                              <?php }) ?>
                              <?php is_allowed('form_dekubitus_delete', function() use ($form_dekubitus){?>
                              <a href="javascript:void(0);" data-href="<?= site_url('administrator/form_dekubitus/delete/' . $form_dekubitus->idform_dekubitus); ?>" class="label-default remove-data"><i class="fa fa-close"></i> <?= cclang('remove_button'); ?></a>
                               <?php }) ?>

                           </td>                        </tr>
                      <?php endforeach; ?>
                      <?php if ($form_dekubitus_counts == 0) :?>
                         <tr>
                           <td colspan="100">
                           Form Dekubitus data is not available
                           </td>
                         </tr>
                      <?php endif; ?>

                     </tbody>
                  </table>
                  </div>
               </div>
               <hr>
             
            </div>
            </form>            
            <!--/box body -->
         </div>
         <!--/box -->
      </div>
   </div>
</section>
<!-- /.content -->

<!-- Page script -->

<script>
  $(document).ready(function(){
   
    (function(){

})()
      
      
      $('.table tbody tr').each(function(){
         var row = $(this);
         (function(){
    var nama_pasien = row.find('.list_group-nama_pasien');
    var nama_ruangan = row.find('.list_group-nama_ruangan');
    var Tanggal_lahir = row.find('.list_group-Tanggal_lahir');
    var Tanggal = row.find('.list_group-Tanggal');
    var Jam = row.find('.list_group-Jam');
    var Jenis_kelamin = row.find('.list_group-Jenis_kelamin');
    var kondisi_fisik = row.find('.list_group-kondisi_fisik');
    var status_mental = row.find('.list_group-status_mental');
    var aktifitas = row.find('.list_group-aktifitas');
    var mobilitas = row.find('.list_group-mobilitas');
    var inkontinensia = row.find('.list_group-inkontinensia');

})()
      })
      
    $('.remove-data').click(function(){

      var url = $(this).attr('data-href');

      swal({
          title: "<?= cclang('are_you_sure'); ?>",
          text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",
          type: "warning",
          showCancelButton: true,
          confirmButtonColor: "#DD6B55",
          confirmButtonText: "<?= cclang('yes_delete_it'); ?>",
          cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",
          closeOnConfirm: true,
          closeOnCancel: true
        },
        function(isConfirm){
          if (isConfirm) {
            document.location.href = url;            
          }
        });

      return false;
    });


    $('#apply').click(function(){

      var bulk = $('#bulk');
      var serialize_bulk = $('#form_form_dekubitus').serialize();

      if (bulk.val() == 'delete') {
         swal({
            title: "<?= cclang('are_you_sure'); ?>",
            text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "<?= cclang('yes_delete_it'); ?>",
            cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",
            closeOnConfirm: true,
            closeOnCancel: true
          },
          function(isConfirm){
            if (isConfirm) {
               document.location.href = BASE_URL + '/administrator/form_dekubitus/delete?' + serialize_bulk;      
            }
          });

        return false;

      } else if(bulk.val() == '')  {
          swal({
            title: "Upss",
            text: "<?= cclang('please_choose_bulk_action_first'); ?>",
            type: "warning",
            showCancelButton: false,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "Okay!",
            closeOnConfirm: true,
            closeOnCancel: true
          });

        return false;
      }

      return false;

    });/*end appliy click*/


    //check all
    var checkAll = $('#check_all');
    var checkboxes = $('input.check');

    checkAll.on('ifChecked ifUnchecked', function(event) {   
        if (event.type == 'ifChecked') {
            checkboxes.iCheck('check');
        } else {
            checkboxes.iCheck('uncheck');
        }
    });

    checkboxes.on('ifChanged', function(event){
        if(checkboxes.filter(':checked').length == checkboxes.length) {
            checkAll.prop('checked', 'checked');
        } else {
            checkAll.removeProp('checked');
        }
        checkAll.iCheck('update');
    });
    initSortable('form_dekubitus', $('table.dataTable'));
  }); /*end doc ready*/
</script>